[package]
name = "rssbot"
version = "1.4.1"
authors = ["iovxw <iovxw@outlook.com>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://github.com/iovxw/rssbot"
repository = "https://github.com/iovxw/rssbot"
publish = false

[workspace]

[dependencies]
log = "0.3"
env_logger = "0.4"
lazy_static = "0.2"
regex = "0.2"
pinyin-order = "0.1"
futures-await = "0.1"
quick-xml = "0.9"
error-chain = "0.10"
chrono = "0.4"

telebot = { path = "./telebot" }
# version specified by telebot
serde = "*"
serde_derive = "*"
serde_json = "*"
curl = "*"
futures = "*"
tokio-core = "*"
tokio-curl = "*"
